name: Keep Alive Render

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping frontend
        run: curl -I --max-time 10 https://portfolio-docker-stack.onrender.com

      - name: Ping backend
        run: curl -I --max-time 10 https://portfolio-docker-stack-bakend.onrender.com
